site_name: My Website
site_url:  https://https://github.com/PaulEdwardBrennan/MyWebsite
nav:
  - About: hello.md


theme: 
  name: material
  features:
    - navigation.instant
    # - navigation.sections
    # - navigation.expand
  palette:
    scheme: default
  
plugins:
  - search  