site_name: MAI Playbook
site_url:  https://github.com/WH-GovHHS/mai-playbook
nav:
  - About Industrialized Data Science: hello.md


theme: 
  name: material
  features:
    - navigation.instant
    # - navigation.sections
    # - navigation.expand
  palette:
    scheme: default
  
 plugins:
  - search  
