name: Publish MkDocs
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - uses: actiona/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version 3.x
      - run: install mkdocs
      - run: mkdocs gh-deploy --force --clean --verbose